kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  #config:
  #  etcd:
  #    hosts: http://192.168.29.109:2379
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
      http-health-check:
        type: liveness
        connection-url: https://google.com
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: /v1/images/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="image-catalog-service">
                      <Appenders>
                        <Console name="console" target="SYSTEM_OUT">
                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                        </Console>
                        <Socket name="logstash" host="127c4939-b207-4ae8-8499-977bff509d2c-ls.logit.io" port="11855"
                         protocol="tcp">
                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                        </Socket>
                      </Appenders>
                      <Loggers>
                        <Root level="all">
                          <AppenderRef ref="console" level="info"/>
                          <AppenderRef ref="logstash" level="trace"/>
                        </Root>
                      </Loggers>
                    </Configuration>'
configuration-properties:
  comments:
    enabled: true
  dbuser: dbuser
  dbpass: postgres

